#!/usr/bin/env python
# coding: utf-8

# ### Feature names

# In[2]:


U_NODE_ID = "U_NODE_ID"
V_NODE_ID = "V_NODE_ID"

U_X = "U_X"
U_Y = "U_Y"

V_X = "V_X"
V_Y = "V_Y"

IS_DEPOT = "IS_DEPOT"

IS_OPTIMAL_EDGE = "IS_OPTIMAL_EDGE"
EDGE_WEIGHT = "EDGE_WEIGHT"

GLOBAL_RANK = "GLOBAL_RANK"
U_NODE_LOCAL_EDGE_RANK = "U_NODE_LOCAL_EDGE_RANK"
V_NODE_LOCAL_EDGE_RANK = "V_NODE_LOCAL_EDGE_RANK"

U_NODE_DEGREE = "U_NODE_DEGREE"
V_NODE_DEGREE = "V_NODE_DEGREE"
AVERAGE_NODE_DEGREE = "AVERAGE_NODE_DEGREE"

U_NODE_CLUSTERING = "U_NODE_CLUSTERING"
V_NODE_CLUSTERING = "V_NODE_CLUSTERING"
AVERAGE_NODE_CLUSTERING = "AVERAGE_NODE_CLUSTERING"

IS_MST_EDGE = "IS_MST_EDGE"
MST_WEIGHT = "MST_WEIGHT"
MST_U_DEGREE = "MST_U_DEGREE"
MST_V_DEGREE = "MST_V_DEGREE"

LP_RELAXATION = "LP_RELAXATION"

FILE_NAME = "FILE_NAME"
U_NODE_DEMAND = "U_NODE_DEMAND"
V_NODE_DEMAND = "V_NODE_DEMAND"
CAPACITY = "CAPACITY"
NUM_OF_VEHICLES = "NUM_OF_VEHICLES"

U_NODE_DEMAND_CAPACITY_RATIO = "U_NODE_DEMAND_CAPACITY_RATIO"
V_NODE_DEMAND_CAPACITY_RATIO = "V_NODE_DEMAND_CAPACITY_RATIO"

REDUCED_COST = "REDUCED_COST"

# In[3]:


column_names = [
    U_NODE_ID,
    V_NODE_ID,
    U_X,
    U_Y,
    V_X,
    V_Y,
    IS_DEPOT,
    IS_OPTIMAL_EDGE,
    EDGE_WEIGHT,
    GLOBAL_RANK,
    U_NODE_LOCAL_EDGE_RANK,
    V_NODE_LOCAL_EDGE_RANK,
    U_NODE_DEGREE, 
    V_NODE_DEGREE, 
    AVERAGE_NODE_DEGREE, 
    U_NODE_CLUSTERING, 
    V_NODE_CLUSTERING, 
    AVERAGE_NODE_CLUSTERING,
    IS_MST_EDGE,
    MST_U_DEGREE,
    MST_V_DEGREE,
    LP_RELAXATION,
    FILE_NAME,
    U_NODE_DEMAND,
    V_NODE_DEMAND,
    CAPACITY,
    NUM_OF_VEHICLES,
    U_NODE_DEMAND_CAPACITY_RATIO,
    V_NODE_DEMAND_CAPACITY_RATIO,
    REDUCED_COST
]

